import './globals.css'
import 'bootstrap/dist/css/bootstrap.css'
import { Inconsolata, Inter } from 'next/font/google'
import Provider from '@/components/Provider'
import Nav from '@/components/Nav'
import { UberProvider } from '@/context/uberContext'

const inter = Inter({ subsets: ['latin'] })
const inconsolata=Inconsolata({subsets:['latin']})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <UberProvider>
      <html lang="en">
        <body className={inter.className}>   
            <Provider>
              
                <main className='app'>
                    <Nav />
                    {children}
                </main>
              
            </Provider>     
        </body>
      </html>
    </UberProvider>
  )
}
